# Generated by Django 3.2.4 on 2022-03-13 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0004_auto_20220313_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='author',
        ),
        migrations.AddField(
            model_name='publications',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_publications', to='auth.user', verbose_name='Авторы публикации'),
            preserve_default=False,
        ),
    ]
