# Generated by Django 3.2.4 on 2022-03-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_auto_20220313_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publications',
            name='images',
        ),
        migrations.AddField(
            model_name='publications',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Изображения'),
            preserve_default=False,
        ),
    ]
