# Generated by Django 3.2.4 on 2022-03-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_remove_publications_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
