# Generated by Django 3.2.4 on 2022-03-13 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='education',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='git',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='telegram',
        ),
    ]
